/*
--------------------------------------------------------------------------------

	Revelation Shaders

	Copyright (C) 2026 HaringPro
	Apache License 2.0

--------------------------------------------------------------------------------
*/

//======// Input //===============================================================================//

layout (local_size_x = 16, local_size_y = 16) in;
const ivec3 workGroups = ivec3(2, 2, 1);

//======// Utility //=============================================================================//

#include "/lib/Utility.glsl"

//======// Uniform //=============================================================================//

writeonly uniform image2D msLutImg;

#include "/lib/universal/Uniform.glsl"

//======// Function //============================================================================//

#include "/lib/atmosphere/Common.glsl"

#include "/lib/universal/Random.glsl"

mat2x3 RaymarchMultiScattering(vec3 rayPos, vec3 rayDir, vec3 sunDir) {
    float topDist = RaySphereIntersectNearest(rayPos, rayDir, atmosphere.topRadius);
    float bottomDist = RaySphereIntersectNearest(rayPos, rayDir, atmosphere.bottomRadius);
    float tMax = topDist;
    if (bottomDist > 0.0) {
        tMax = bottomDist;
    }

    float stepSize = tMax * rcp(32.0);
    vec3 rayStep = stepSize * rayDir;
    rayPos += 0.5 * rayStep;

    vec3 lum = vec3(0.0), fms = vec3(0.0), transmittance = vec3(1.0);
    for (uint i = 0u; i < 16u; ++i, rayPos += rayStep) {
        vec3 density = AtmosphereDensityAtPoint(rayPos);
        vec3 extinction = atmosphereExtinction * density;

        vec3 sampleTransmittance = exp(-stepSize * extinction);

        vec3 inScattering = atmosphereScattering * density.xy;
        vec3 scatteringIntegral = (inScattering - inScattering * sampleTransmittance) / extinction;
        fms += scatteringIntegral * transmittance;

        vec3 sunTransmittance = AtmosphereTransmittanceToSun(rayPos, sunDir);
        scatteringIntegral *= uniformPhase * sunTransmittance;

        lum += scatteringIntegral * transmittance;
        transmittance *= sampleTransmittance;
    }

    // Ground diffuse
    if (bottomDist > 0.0) {
        vec3 planetPos = rayPos + rayDir * bottomDist;
        float planetHeight = length(planetPos);
        vec3 upVector = planetPos / planetHeight;

        vec3 transmittanceToSun = AtmosphereTransmittanceToSun(planetHeight, dot(upVector, sunDir));
        float NdotL = saturate(dot(upVector, sunDir));
        lum += atmosphere.groundAlbedo * rPI * NdotL * transmittance * transmittanceToSun;
    }

    return mat2x3(lum, fms);
}

//======// Main //================================================================================//
void main() {
	ivec2 tid = ivec2(gl_GlobalInvocationID.xy);
	vec2 uv = (vec2(tid) + 0.5) * rcp(imageSize(msLutImg));

    float cosTheta = uv.x * 2.0 - 1.0;
    float height = mix(atmosphere.bottomRadius, atmosphere.topRadius, uv.y);

    vec3 rayPos = vec3(0.0, height, 0.0);
    vec3 sunDir = normalize(vec3(0.0, cosTheta, sqrt(1.0 - cosTheta * cosTheta)));

    const uint samples = 64u;
    const float rSamples = 1.0 / float(samples);

    mat2x3 sum = mat2x3(0.0);
	for (uint i = 0u; i < samples; ++i) {
        vec3 rayDir = SampleUniformSphere(R2(i));
        sum += RaymarchMultiScattering(rayPos, rayDir, sunDir);
	}
    sum *= rSamples;

	imageStore(msLutImg, tid, vec4(sum[0] / (1.0 - sum[1]), 1.0));
}