/*
--------------------------------------------------------------------------------

	Revelation Shaders

	Copyright (C) 2026 HaringPro
	Apache License 2.0

--------------------------------------------------------------------------------
*/

//======// Input //===============================================================================//

layout (local_size_x = 16, local_size_y = 16) in;
const ivec3 workGroups = ivec3(12, 12, 1);

//======// Utility //=============================================================================//

#include "/lib/Utility.glsl"

//======// Uniform //=============================================================================//

writeonly restrict uniform image2D skyViewImg;

#include "/lib/universal/Uniform.glsl"

//======// Function //============================================================================//

#include "/lib/atmosphere/Common.glsl"
#include "/lib/universal/Random.glsl"

vec3 RaymarchScattering(vec3 rayPos, vec3 rayDir, vec3 sunDir, float tMax) {
    float cosTheta = dot(rayDir, sunDir);
    vec2 phaseValue = AtmospherePhase(cosTheta);

    // Adaptive sample count
	float sampleCount = round(mix(8.0, 16.0, saturate(tMax * 1e-5)));

    float stepSize = tMax * rcp(sampleCount);
    vec3 rayStep = stepSize * rayDir;
    rayPos += 0.5 * rayStep;

    vec3 lum = vec3(0.0);
    vec3 transmittance = vec3(1.0);
    for (uint i = 0u; i < uint(sampleCount); ++i, rayPos += rayStep) {
        vec3 density = AtmosphereDensityAtPoint(rayPos);
        vec3 extinction = atmosphereExtinction * density;

        vec3 sunTransmittance = AtmosphereTransmittanceToSun(rayPos, sunDir);
        vec3 psiMs = AtmosphereMultiScattering(rayPos, sunDir);

        vec3 inScattering = atmosphereScattering * (density.xy * phaseValue) * sunTransmittance;
        inScattering += atmosphereScattering * density.xy * psiMs;

        vec3 sampleTransmittance = exp(-stepSize * extinction);

        vec3 scatteringIntegral = (inScattering - inScattering * sampleTransmittance) / extinction;
        lum += scatteringIntegral * transmittance;

        transmittance *= sampleTransmittance;
    }
    return lum;
}

vec3 RenderSkyView(vec2 uv) {
    float lightViewCos = 1.0 - sqr(uv.x) * 2.0;
    float height = atmosphereViewHeight;
    vec3 up = vec3(0.0, 1.0, 0.0);

    float vHorizon = sqrt(height * height - atmosphere.bottomRadius * atmosphere.bottomRadius);
    float beta = fastAcos(vHorizon / height);
    float zenithHorizon = PI - beta;

    float viewZenithCos;
    if (uv.y < 0.5) {
        float coord = 1.0 - 2.0 * uv.y;
        coord *= coord; // Non-linear mapping
        viewZenithCos = cos(zenithHorizon * (1.0 - coord));
    } else {
        float coord = uv.y * 2.0 - 1.0;
        coord *= coord; // Non-linear mapping
        viewZenithCos = cos(zenithHorizon + beta * coord);
    }
    float viewZenithSin = sqrt(1.0 - viewZenithCos * viewZenithCos);
    vec3 rayDir = vec3(viewZenithSin * lightViewCos, viewZenithCos, viewZenithSin * sqrt(1.0 - lightViewCos * lightViewCos));

    float sunZenithCos = dot(up, worldSunDir);
    vec3 sunDir = normalize(vec3(sqrt(1.0 - sunZenithCos * sunZenithCos), sunZenithCos, 0.0));

    float topDist = RaySphereIntersectNearest(atmosphereViewPos, rayDir, atmosphere.topRadius);
    float bottomDist = RaySphereIntersectNearest(atmosphereViewPos, rayDir, atmosphere.bottomRadius);

    if (topDist < 0.0 && bottomDist < 0.0) {
        return vec3(0.0); // No intersection with atmosphere nor earth
    }

    vec3 lum = vec3(0.0);
    if (bottomDist < 0.0) {
        lum = RaymarchScattering(atmosphereViewPos, rayDir, sunDir, topDist);
        lum += RaymarchScattering(atmosphereViewPos, rayDir, -sunDir, topDist) * moonlightMult;
    } else {
        lum = RaymarchScattering(atmosphereViewPos, rayDir, sunDir, bottomDist);
        lum += RaymarchScattering(atmosphereViewPos, rayDir, -sunDir, bottomDist) * moonlightMult;

        vec3 planetPos = atmosphereViewPos + rayDir * bottomDist;
        vec3 sunTransmittance = AtmosphereTransmittanceToSun(planetPos, sunDir);
        vec3 moonTransmittance = AtmosphereTransmittanceToSun(planetPos, -sunDir);

        vec3 t1 = AtmosphereTransmittanceToPoint(planetPos, -rayDir);
        vec3 t2 = AtmosphereTransmittanceToPoint(atmosphereViewPos, -rayDir);
        vec3 aerialT = saturate(t1 / t2);

        float NdotL = abs(dot(normalize(planetPos), sunDir));
        vec3 lambertian = atmosphere.groundAlbedo * NdotL * rPI;

        lum += lambertian * (sunTransmittance + moonTransmittance * moonlightMult) * aerialT;
    }

    lum = desaturate(lum, wetness * 0.5); // Post-process
    return lum * 128.0;
}

//======// Main //================================================================================//
void main() {
	ivec2 tid = ivec2(gl_GlobalInvocationID.xy);
	vec2 uv = (vec2(tid) + 0.5) * rcp(imageSize(skyViewImg));

	imageStore(skyViewImg, tid, vec4(RenderSkyView(uv), 1.0));
}