/*
--------------------------------------------------------------------------------

	Revelation Shaders

	Copyright (C) 2026 HaringPro
	Apache License 2.0

--------------------------------------------------------------------------------
*/

//======// Input //===============================================================================//

layout (local_size_x = 16, local_size_y = 16) in;
const ivec3 workGroups = ivec3(16, 16, 1);

//======// Utility //=============================================================================//

#include "/lib/Utility.glsl"

//======// Uniform //=============================================================================//

layout (rgba16f) restrict uniform image2D skyViewImg;

#include "/lib/universal/Uniform.glsl"

//======// Function //============================================================================//

#include "/lib/atmosphere/Common.glsl"
#include "/lib/universal/Random.glsl"

vec3 RaymarchScattering(vec3 rayPos, vec3 rayDir, vec3 sunDir, float tMax, float dither) {
    float cosTheta = dot(rayDir, sunDir);

	float rayleighPhase = RayleighPhase(cosTheta);
	float miePhase = AerosolPhase(cosTheta);

    float stepSize = tMax * rcp(32.0);
    vec3 rayStep = stepSize * rayDir;
    rayPos += dither * rayStep;

    vec3 lum = vec3(0.0);
    vec3 transmittance = vec3(1.0);
    for (uint i = 0u; i < 32u; ++i, rayPos += rayStep) {
        vec3 density = AtmosphereDensityAtPoint(rayPos);
        vec3 extinction = AtmosphereExtinctionFromDensity(density);

        vec3 rayleighScattering = atmosphere.rayleighScattering * density.x;
        vec3 mieScattering = atmosphere.mieScattering * density.y;

        vec3 sunTransmittance = AtmosphereTransmittance(rayPos, sunDir);
        vec3 psiMs = AtmosphereMultiScattering(rayPos, sunDir);

        vec3 rayleighInScattering = rayleighScattering * (rayleighPhase * sunTransmittance + psiMs);
        vec3 mieInScattering = mieScattering * (miePhase * sunTransmittance + psiMs);
        vec3 inScattering = (rayleighInScattering + mieInScattering);

        vec3 sampleTransmittance = exp(-stepSize * extinction);

        vec3 scatteringIntegral = (inScattering - inScattering * sampleTransmittance) / extinction;
        lum += scatteringIntegral * transmittance;

        transmittance *= sampleTransmittance;
    }
    return lum;
}

vec3 RenderSkyView(vec2 uv, float dither) {
    float lightViewCos = 1.0 - sqr(uv.x) * 2.0;
    float height = atmosphereViewHeight;
    vec3 up = vec3(0.0, 1.0, 0.0);

    float vHorizon = sqrt(height * height - atmosphere.bottomRadius * atmosphere.bottomRadius);
    float beta = fastAcos(vHorizon / height);
    float zenithHorizon = PI - beta;

    float viewZenithCos;
    if (uv.y < 0.5) {
        float coord = 1.0 - 2.0 * uv.y;
        coord *= coord; // Non-linear mapping
        viewZenithCos = cos(zenithHorizon * (1.0 - coord));
    } else {
        float coord = uv.y * 2.0 - 1.0;
        coord *= coord; // Non-linear mapping
        viewZenithCos = cos(zenithHorizon + beta * coord);
    }
    float viewZenithSin = sqrt(1.0 - viewZenithCos * viewZenithCos);
    vec3 rayDir = vec3(viewZenithSin * lightViewCos, viewZenithCos, viewZenithSin * sqrt(1.0 - lightViewCos * lightViewCos));

    float sunZenithCos = dot(up, worldSunDir);
    vec3 sunDir = normalize(vec3(sqrt(1.0 - sunZenithCos * sunZenithCos), sunZenithCos, 0.0));

    float topDist = RaySphereIntersectNearest(atmosphereViewPos, rayDir, atmosphere.topRadius);
    float bottomDist = RaySphereIntersectNearest(atmosphereViewPos, rayDir, atmosphere.bottomRadius);

    vec3 lum = vec3(0.0);
    if (bottomDist < 0.0) {
        lum = RaymarchScattering(atmosphereViewPos, rayDir, sunDir, topDist, dither);
    } else {
        lum = RaymarchScattering(atmosphereViewPos, rayDir, sunDir, bottomDist, dither);
        vec3 planetPos = atmosphereViewPos + rayDir * bottomDist;
        vec3 sunTransmittance = AtmosphereTransmittance(planetPos, sunDir);

        vec3 t1 = AtmosphereTransmittance(planetPos, -rayDir);
        vec3 t2 = AtmosphereTransmittance(atmosphereViewPos, -rayDir);
        vec3 aerialT = t1 / t2;

        float NdotL = dot(normalize(planetPos), sunDir);
        vec3 lambertian = atmosphere.groundAlbedo * NdotL * rPI;

        lum += lambertian * sunTransmittance * aerialT;
    }

    lum = desaturate(lum, wetness * 0.5); // Post-process
    return lum * 683.0;
}

//======// Main //================================================================================//
void main() {
	ivec2 tid = ivec2(gl_GlobalInvocationID.xy);
	vec2 uv = (vec2(tid) + 0.5) * rcp(imageSize(skyViewImg));

    float dither = BlueNoise(tid, frameCounter);

    vec3 result = imageLoad(skyViewImg, tid).rgb;
    result = mix(result, RenderSkyView(uv, dither), rcp(min(frameCounter, 64)));

	imageStore(skyViewImg, tid, vec4(result, 1.0));
}