/*
--------------------------------------------------------------------------------

	Revelation Shaders

	Copyright (C) 2026 HaringPro
	Apache License 2.0

--------------------------------------------------------------------------------
*/

//======// Input //===============================================================================//

layout (local_size_x = 16, local_size_y = 16) in;
const ivec3 workGroups = ivec3(16, 4, 1);

//======// Utility //=============================================================================//

#include "/lib/Utility.glsl"

//======// Uniform //=============================================================================//

writeonly uniform image2D tLutImg;

#include "/lib/universal/Uniform.glsl"

//======// Function //============================================================================//

#include "/lib/atmosphere/Common.glsl"

vec3 RaymarchSunTransmittance(vec3 rayPos, vec3 rayDir) {
    // Intersect ground
    if (RaySphereIntersectNearest(rayPos, rayDir, atmosphere.bottomRadius) > 0.0) {
        return vec3(0.0);
    }

    float stepSize = RaySphereIntersectNearest(rayPos, rayDir, atmosphere.topRadius) * rcp(64.0);
    vec3 rayStep = stepSize * rayDir;
    rayPos += 0.5 * rayStep;

    vec3 od = vec3(0.0);
    for (uint i = 0u; i < 64u; ++i, rayPos += rayStep) {
        vec3 density = AtmosphereDensityAtPoint(rayPos);
        od += AtmosphereExtinctionFromDensity(density);
    }
    return exp(-stepSize * od);
}

//======// Main //================================================================================//
void main() {
	ivec2 tid = ivec2(gl_GlobalInvocationID.xy);
	vec2 uv = (vec2(tid) + 0.5) * rcp(imageSize(tLutImg));

    float cosTheta = 2.0 * uv.x - 1.0;
    float height = mix(atmosphere.bottomRadius, atmosphere.topRadius, uv.y);

    vec3 rayPos = vec3(0.0, height, 0.0);
    vec3 sunDir = normalize(vec3(0.0, cosTheta, sqrt(1.0 - cosTheta * cosTheta)));

	imageStore(tLutImg, tid, vec4(RaymarchSunTransmittance(rayPos, sunDir), 1.0));
}